#!/bin/bash
ifwan=Placa de Rede WAN
iflan=Placa de Rede LAN
iniciar () {
        echo "Iniciando Servico de Firewall"
        echo "Estabelecendo Regras"
        modprobe iptable_nat
        echo 1 > /proc/sys/net/ipv4/ip_forward
        iptables -t nat -A POSTROUTING -o $ifwan -j MASQUERADE
#       iptables -t nat -A PREROUTING -i $iflan -p tcp --dport 80 -j \REDIRECT --to-port 3128 #Somente se usar o Squid
        iptables -A INPUT -p icmp --icmp-type echo-request -j DROP
        iptables -A FORWARD -m string --algo bm --string "facebook.com" -j REJECT
        iptables -A INPUT -i lo -j ACCEPT
        iptables -A INPUT -i $iflan -j ACCEPT
        iptables -A INPUT -p tcp --dport 22 -j ACCEPT
        iptables -A INPUT -p tcp --dport 21 -j DROP
        iptables -A INPUT -p tcp --dport 69 -j DROP
        iptables -A INPUT -p tcp --syn -j DROP

}
parar() {
        echo "Encerrando o Firewall"
        echo "Apagando tables"
        iptables -F
        iptables -F -t nat
}
case "$1" in
        "start") iniciar ;;
        "stop") parar ;;
        "restart") parar ; iniciar ;;
        *) echo "Erro de sintaxe, use start, stop ou restart"

esac
